#!/bin/bash

# build react frontend
cd frontend
npm install -g npm
npm install
npm run build
cd ..

# copy react production build to assets folder
sudo rm -r cen_uiu/assets/static
cp -r frontend/build/* cen_uiu/assets/