#!/bin/bash

/usr/bin/chromium --app=http://localhost:4123/index.html --start-fullscreen --noerrdialogs --disable-translate --no-first-run --fast --fast-start --disable-infobars --disable-features=TranslateUI --kiosk --password-store=basic