#!/bin/bash

chromium http://localhost:4123/index.html --start-fullscreen --noerrdialogs --disable-translate --no-first-run --fast --fast-start --disable-infobars --disable-features=TranslateUI --password-store=basic