#!/bin/bash

apt install dnsmasq hostapd

# stop services
systemctl stop dnsmasq
systemctl stop hostapd

# dns service for the hotspot
cat <<'EOF' > /etc/dhcpcd.conf
hostname
clientid
persistent
option rapid_commit
option domain_name_servers, domain_name, domain_search, host_name
option classless_static_routes
option interface_mtu
require dhcp_server_identifier
slaac private
interface wlan0
static ip_address = 192.168.4.1/24
EOF

systemctl restart dhcpcd

# dns mask config
mv /etc/dnsmasq.conf /etc/dnsmasq.conf.orig
cat <<'EOF' > /etc/dhcpcd.conf
interface=wlan0
dhcp-range=192.168.4.2,192.168.4.20,255.255.255.0,24h
EOF

# hotspot settings
touch /etc/hostapd/hostapd.conf
cat <<'EOF' > /etc/hostapd/hostapd.conf
interface=wlan0
driver=nl80211
ssid=Chevrolet-Matiz
hw_mode=g
channel=7
wmm_enabled=0
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase=
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
EOF

cat <<'EOF' > /etc/default/hostapd
DAEMON_CONF="/etc/hostapd/hostapd.conf"
EOF

# start everything
systemctl unmask hostapd
systemctl start hostapd
systemctl start dnsmasq