#!/bin/bash

sudo raspi-config nonint do_hostname "matiz"
sudo hostnamectl set-hostname --pretty "Chevrolet Matiz"

sudo apt install -y --no-install-recommends alsa-base alsa-utils bluealsa bluez-tools

cat <<'EOF' > /etc/bluetooth/main.conf
[General]
Class = 0x20041C
DiscoverableTimeout = 0
[Policy]
AutoEnable=true
EOF