#!/bin/bash

sudo scripts/setup-bluetooth
sudo scripts/setup-services

sudo apt install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev

python3 -m venv venv
source ./venv/bin/activate

python3 -m pip install -e .