#!/bin/bash

sudo apt update

sudo scripts/setup-bluetooth
#sudo scripts/setup-wifi
#sudo scripts/setup-services

# install linux packages
sudo apt install -y python3-gi python3-gi-cairo gir1.2-gtk-3.0 gir1.2-webkit2-4.0 libgirepository1.0-dev libcairo2-dev
sudo apt install -y pkg-config libboost-python-dev libboost-thread-dev libbluetooth-dev libglib2.0-dev python-dev libboost-dev sed

# build react frontend
scripts/build-react

# create python virtual enviroment
python3 -m venv venv
source ./venv/bin/activate
pip install wheel

# temporary folder for build files
mkdir temp
cd temp

# build/install gattlib
pip3 download gattlib
tar xvzf ./gattlib-*.tar.gz
cd gattlib-*/
sed -ie 's/boost_python-py34/boost_python37/' setup.py
pip install .

cd ..

# build/install pybluez with ble
git clone https://github.com/pybluez/pybluez.git
cd pybluez
git pull
pip install -e .[ble]

cd ../../

# clean up
sudo rm -r temp

python3 -m pip install -e .