#pragma once

#include <ChRt.h>

#define RGB_BUTTON_SHORT_PRESS_EVT EVENT_MASK(0)
#define RGB_BUTTON_LONG_PRESS_EVT EVENT_MASK(1)
#define IGNITION_ON_EVENT EVENT_MASK(2)
#define IGNITION_OFF_EVENT EVENT_MASK(3)